#build only for unstable branch
branches:
   only:
     - unstable

language: objective-c
osx_image: xcode7.2

env:
  matrix:
    - SDK=iphonesimulator9.2 OS=9.2 NAME="iPhone 6" SCHEME=UnitTests
    - SDK=iphonesimulator9.2 OS=9.2 NAME="iPad 2" SCHEME=UnitTestsNoSyncNoMRU

before_install:
   - gem install xcpretty
   - npm install shelljs@0.7.0
   - brew update
   - brew install ant

#before the script is run for the build, inject data into test_credentials file
before_script:
   - ./build/pre-build

script:
   #run template app generation
   # - travis_wait 30 set -o pipefail && node external/shared/node/test_force.js --os=ios --test=native
   # - travis_wait 30 set -o pipefail && node external/shared/node/test_force.js --os=ios --test=native_swift
   # - travis_wait 30 set -o pipefail && node external/shared/node/test_force.js --os=ios --test=react_native
   # build libs
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceAnalytics CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceSDKCore CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SmartStore CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSync CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceHybridSDK CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SalesforceReact CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   # build native sample apps
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme RestAPIExplorer CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncExplorer CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   # build hybrid sample apps
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme AccountEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme NoteSync CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'
   - set -o pipefail && xcodebuild -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncExplorerHybrid CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty --simple --color | grep -v 'Compiling'

   # run unit tests that don't need a host app
   - travis_wait 30 set -o pipefail && xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme $SCHEME -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS" | xcpretty --color --simple --test
    
   # run UI tests that need a host app
   - set -o pipefail && xcodebuild test -workspace SalesforceMobileSDK.xcworkspace -scheme SmartSyncExplorer -sdk $SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS"

