#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
#  NOTE: When updaing Xcode check the manifest for compatible chruby versions.
anchors:
  - &latest-xcode    "14.3.1"
  - &latest-ios      "16.4"
  - &min-ios         "15.5"
  - &requres-string  "test << matrix.lib >> iOS 15.5"  # Keep this version up to date
  - &chruby          "3.1.4"
  - &device          "iPhone 13"
  - &invalid         ""

executors:
  mac:
    macos:
      xcode: *latest-xcode

version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceSDKCommon"
      nightly-test:
        type: boolean
        default: false
      xcode:
        type: string
        default: *latest-xcode
      ios:
        type: string
        default: *latest-ios
      chruby:
        type: string
        default: *chruby
      device:
        type: string
        default: *device
    macos:
      xcode: << parameters.xcode >>
    working_directory: ~/SalesforceMobileSDK-iOS
    shell: /bin/bash --login -eo pipefail
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: << parameters.chruby >>
      LIB: << parameters.lib >>
      NIGHTLY_TEST: << parameters.nightly-test >>
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v8-gems-{{ checksum ".circleci/Gemfile.lock" }}
            - v8-gems-
      - run: 
          name: Install Dependencies
          command:  |
            npm install shelljs@0.8.5
            ./install.sh
            ./build/pre-build
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle check || sudo bundle install
            sudo bundle update
      - save_cache: 
          key: v8-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/<< parameters.chruby >>
      - run: 
          name: Run Tests
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle exec fastlane PR lib:<< parameters.lib >> 
      - run: 
          name: Danger Lib
          command:  |
            chruby ${CHRUBY_VER}
            danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis

#  Potential parameters that can come from the project GUI Triggers
parameters:
  xcode:
    type: string
    default: *invalid
  ios:
    type: string
    default: *invalid
  chruby:
    type: string
    default: *chruby
  device:
    type: string
    default: *device
      
workflows:
  version: 2

  build-test-pr:
    when: 
      and:
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          matrix:
            parameters:
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
          filters:
            branches:
              only:
                - /pull.*/

  # Build everything at 10 PM PST Tuesday/Thursday Nights
  run-tests:
    when:
      and:
        - not: << pipeline.parameters.xcode >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          matrix:
            parameters:
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
              nightly-test: [true]
              ios: [*min-ios]
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          matrix:
            parameters:
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
              nightly-test: [true]
              ios: [*latest-ios]
          requires:
            - *requres-string

  # Build everything at 11 PM PST Tuesday/Thursday Nights
  run-tests-beta:
    when:
      and:
        - << pipeline.parameters.xcode >>
        - << pipeline.parameters.ios >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          matrix:
            parameters:
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              chruby: [<< pipeline.parameters.chruby >>]
              device: [<< pipeline.parameters.device >>]
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
              nightly-test: [true]
            
