aliases:
  - &save-gem-cache
    key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
    paths:
      - /Users/distiller/.gem/ruby/2.5.1
      - /Users/distiller/.rubies/ruby-2.4.2/lib/ruby/gems/2.5.1

  - &restore-gem-cache
    keys:
      - v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
      - v5-gems-

  - &install-dependecies
    name: Install Dependencies
    command:  |
      npm install shelljs@0.7.0
      ./install.sh
      ./build/pre-build
      chruby ${CHRUBY_VER}
      cd .circleci
      bundle check || sudo bundle install
      sudo bundle update

  - &run-tests
    name: Run Tests
    command:  |
      chruby ${CHRUBY_VER}
      cd .circleci
      fastlane ${FASTLANE_LANE}

  - &danger-lib
    name: Danger Lib
    command:  |
      chruby ${CHRUBY_VER}
      DANGER_GITHUB_API_TOKEN="b676bc92bde5202b94d0""ec8dfecb2716044bf523" danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
    background: true
    when: always

  - &codecov
    name: Codecov Uplaod
    command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode
    when: always

  - &pr-filter
    filters:
      branches:
        only:
        - /pull.*/

defaults: &defaults
  working_directory: ~/SalesforceMobileSDK-iOS
  macos:
    xcode: "10.1.0"
  shell: /bin/bash --login -eo pipefail
  environment:
    BASH_ENV: ~/.bashrc
    FASTLANE_SKIP_UPDATE_CHECK: true
    CHRUBY_VER: 2.5.3

version: 2
jobs:
  test-SalesforceSDKCommon:
    <<: *defaults
    environment:
      - FASTLANE_LANE: "PR lib:SalesforceSDKCommon"
      - LIB: "SalesforceSDKCommon"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependecies
      - save_cache: *save-gem-cache
      - run: *run-tests
      - run: *danger-lib
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis
      - run: *codecov

  test-SalesforceAnalytics:
    <<: *defaults
    environment:
      - FASTLANE_LANE: "PR lib:SalesforceAnalytics"
      - LIB: "SalesforceAnalytics"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependecies
      - save_cache: *save-gem-cache
      - run: *run-tests
      - run: *danger-lib
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis
      - run: *codecov

  test-SalesforceSDKCore:
    <<: *defaults
    environment:
      - FASTLANE_LANE: "PR lib:SalesforceSDKCore"
      - LIB: "SalesforceSDKCore"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependecies
      - save_cache: *save-gem-cache
      - run: *run-tests
      - run: *danger-lib
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis
      - run: *codecov

  test-SmartStore:
    <<: *defaults
    environment:
      - FASTLANE_LANE: "PR lib:SmartStore"
      - LIB: "SmartStore"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependecies
      - save_cache: *save-gem-cache
      - run: *run-tests
      - run: *danger-lib
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis
      - run: *codecov

  test-SmartSync:
    <<: *defaults
    environment:
      - FASTLANE_LANE: "PR lib:SmartSync"
      - LIB: "SmartSync"
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-dependecies
      - save_cache: *save-gem-cache
      - run: *run-tests
      - run: *danger-lib
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis
      - run: *codecov
      
workflows:
  version: 2

  build-test-pr:
    jobs:
      - test-SalesforceSDKCommon:
          *pr-filter
      - test-SalesforceAnalytics:
          *pr-filter
      - test-SalesforceSDKCore:
          *pr-filter
      - test-SmartStore:
          *pr-filter
      - test-SmartSync:
          *pr-filter
  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~9:30pm Sunday/Wednesday Nights
  nightly-test-ios11:
    triggers:
      - schedule:
          cron: "30 5 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - test-SalesforceSDKCommon:
            context: nightly-test
      - test-SalesforceAnalytics:
            context: nightly-test
      - test-SalesforceSDKCore:
            context: nightly-test
      - test-SmartStore:
            context: nightly-test
      - test-SmartSync:
            context: nightly-test
