#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
anchors:
  - &latest-xcode    "14.3.1"
  - &latest-ios      "16.4"
  - &min-ios         "15.5"
  - &requres-string  "test << matrix.lib >> iOS 15.5"  # Keep this min version up to date
  - &device          "iPhone-SE-3rd-generation"
  - &invalid         ""

executors:
  mac:
    macos:
      xcode: *latest-xcode

version: 2.1
jobs:
  run-tests:
    parameters:
      lib:
        type: string
        default: "SalesforceSDKCommon"
      nightly-test:
        type: boolean
        default: false
      xcode:
        type: string
        default: *latest-xcode
      ios:
        type: string
        default: *latest-ios
      device:
        type: string
        default: *device
    macos:
      xcode: << parameters.xcode >>
    resource_class: macos.m1.medium.gen1
    working_directory: ~/SalesforceMobileSDK-iOS
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      LIB: << parameters.lib >>
      NIGHTLY_TEST: << parameters.nightly-test >>
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v1-gem-cahce-{{ checksum ".circleci/Gemfile.lock" }}
            - v1-gem-cahce
      - run: 
          name: Install Dependencies
          command:  |
            npm install shelljs@0.8.5
            ./install.sh
            ./build/pre-build
            cd .circleci
            bundle check || sudo bundle install --path vendor/bundle
      - save_cache: 
          key: v1-gem-cahce{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: 
          name: Run Tests
          command:  |
            cd .circleci
            bundle exec fastlane PR lib:<< parameters.lib >> 
          no_output_timeout: 20m
      - run: 
          name: Danger Lib
          command:  |
            danger --dangerfile=.circleci/Dangerfile-Lib.rb --danger_id="${LIB}" --verbose
          background: true
          when: always
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/test_output/
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-iOS/clangReport
          destination: Static-Analysis

#  Potential parameters that can come from the project GUI Triggers
parameters:
  xcode:
    type: string
    default: *invalid
  ios:
    type: string
    default: *invalid
  device:
    type: string
    default: *device
      
workflows:
  version: 2

  build-test-pr:
    when: 
      and:
        - equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          context: iOS Unit Tests
          matrix:
            parameters:
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
          filters:
            branches:
              only:
                - /pull.*/

  # Build everything at 10 PM PST Tuesday/Thursday Nights
  run-tests:
    when:
      and:
        - not: << pipeline.parameters.xcode >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          context: iOS Unit Tests
          matrix:
            parameters:
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
              nightly-test: [true]
              ios: [*min-ios]
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          context: iOS Unit Tests 
          matrix:
            parameters:
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
              nightly-test: [true]
              ios: [*latest-ios]
          requires:
            - *requres-string

  # Build everything at 11 PM PST Tuesday/Thursday Nights
  run-tests-beta:
    when:
      and:
        - << pipeline.parameters.xcode >>
        - << pipeline.parameters.ios >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - run-tests:
          name: test << matrix.lib >> iOS << matrix.ios >> 
          context: iOS Unit Tests
          matrix:
            parameters:
              xcode: [<< pipeline.parameters.xcode >>]
              ios: [<< pipeline.parameters.ios >>]
              device: [<< pipeline.parameters.device >>]
              lib: ["SalesforceSDKCommon", "SalesforceAnalytics", "SalesforceSDKCore", "SmartStore", "MobileSync"]
              nightly-test: [true]
            
