name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 3,5"  # cron is UTC, this translates to 10 PM PST Tues and Thur.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceSDKCommon, SalesforceAnalytics, SalesforceSDKCore, SmartStore, MobileSync]
        ios: [^26, ^18, ^17]
        include:
          - ios: ^26
            xcode: ^26
            macos: macos-26
          - ios: ^18
            xcode: ^16
            macos: macos-latest
          - ios: ^17
            xcode: ^16
            macos: macos-latest
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
    secrets: inherit

  native-samples-nightly:
    strategy:
      fail-fast: false
      matrix:
        app: [RestAPIExplorer, MobileSyncExplorer, AuthFlowTester]
        ios: [^26, ^18, ^17]
        include:
          - ios: ^26
            xcode: ^26
            macos: macos-26
          - ios: ^18
            xcode: ^16
            macos: macos-latest
          - ios: ^17
            xcode: ^16
            macos: macos-latest
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.app }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      build_only: true
    secrets: inherit