name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 3,5"  # cron is UTC, this translates to 10 PM PST Tues and Thur.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceSDKCommon, SalesforceAnalytics, SalesforceSDKCore, SmartStore, MobileSync]
        macos: [macos-15]
        ios: [^18]
        xcode: [^26, ^16]
        # Valid combinations that will run:
        # - iOS ^18 + Xcode ^26
        # - iOS ^18 + Xcode ^16
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit

  native-samples-nightly:
    strategy:
      fail-fast: false
      matrix:
        app: [RestAPIExplorer, MobileSyncExplorer]
        macos: [macos-15]
        ios: [^18]
        xcode: [^26, ^16]
        # Valid combinations that will run:
        # - iOS ^18 + Xcode ^26
        # - iOS ^18 + Xcode ^16
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.app }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit